version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodatabase"
    ports:
      - 27017:27017
  app:
    build:
      context: .
    container_name: "template-rest"
    environment:
      MONGO: "mongodb://mongodatabase:27017/template-rest"
    ports:
      - 3000:3000
