# This workflow will run all the checks to see if the code is running fine like tests, linters: eslint and typescript
name: Check Pull Request

on: pull_request

jobs:
  check-eslint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo apt-get install -y mongodb-org=3.6.14 mongodb-org-server=3.6.14 mongodb-org-shell=3.6.14 mongodb-org-mongos=3.6.14 mongodb-org-tools=3.6.14
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Dependencies Installation
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: install --ignore-engines
      - name: ESLint Check
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: eslint:check
      - name: Typescript Check
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: ts:check
      - name: Tests Check
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: test
